fix:resolved sign-up distortion[#2133]
sparrowapp-dev/sparrow-app-auth pull request #86
Opened 2024-12-12 06:17 UTC by aakashreddy-p

Updated the CSS properties so that it can take large emails[#2133].

2024-12-20 14:11 UTC, itsmdasifraza commented on src/pages/Auth/verify-email/VerifyEmail.svelte
>  					</p>
add the limit to crop text, if it  overflows flows

2024-12-20 14:21 UTC, itsmdasifraza commented
Could you change the base branch to development

2024-12-20 14:23 UTC, Astitva877 requested changes
@aakashreddy-p whenever you raise PR, raise it in development not in main.

2024-12-20 16:41 UTC, aakashreddy-p commented on src/pages/Auth/verify-email/VerifyEmail.svelte
>  					</p>
@itsmdasifraza I will fix it.

2024-12-23 08:30 UTC, itsmdasifraza requested changes

2024-12-23 08:30 UTC, itsmdasifraza commented on src/pages/Auth/verify-email/VerifyEmail.svelte
>  	let redirectRules = {
use 
```
   const  MAX_LENGTH = 100;
```

2024-12-23 08:30 UTC, itsmdasifraza commented on src/pages/Auth/verify-email/VerifyEmail.svelte
> +		}
use arrow function here, return type is missing

2024-12-23 08:57 UTC, aakashreddy-p commented on src/pages/Auth/verify-email/VerifyEmail.svelte
>  	let redirectRules = {
okay

2024-12-23 08:57 UTC, aakashreddy-p commented on src/pages/Auth/verify-email/VerifyEmail.svelte
> +		}
I will fix it

2024-12-23 08:57 UTC, aakashreddy-p commented on src/pages/Auth/verify-email/VerifyEmail.svelte
> +	$: EmailText = handleEmail(emailText, maxlength);
I will change it.

2024-12-23 11:26 UTC, closed without merging